import type { Metadata } from "next";
import { Nabla, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import MaxWidthWrapper from "@/lib/main-width-wrapper";
import Header from "@/components/pageComp/header";
import { BackGround } from "@/components/ui/_animatedComp/background";

const poppins = Poppins({ weight: ["400"], subsets: ["latin"] })

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (

      <html lang="en">
         <body className={`${poppins.className} overflow-x-hidden`}>
            <ThemeProvider
               attribute="class"
               defaultTheme="light"
               disableTransitionOnChange
            >
               <Header />
               <main className="container z-10 mx-auto relative">
                  {children}
               </main>
               <BackGround />
            </ThemeProvider>
         </body>
      </html>
   );
}
