import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { IBM_Plex_Serif } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme-provider";
import LoaderWrapper from "@/components/ui/loaderwrapper";
import Footer from "@/components/pageComp/footer";

const poppins = Poppins({ weight: ["400"], subsets: ["latin"] })
const ibmPelx = IBM_Plex_Serif({ weight: ["500"], style: ["italic"], subsets: ["latin"] })

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (

      <html lang="en">
         <body className={`${ibmPelx.className} overflow-x-hidden`}>
            <ThemeProvider
               attribute="class"
               defaultTheme="dark"
               disableTransitionOnChange
            >
               <LoaderWrapper>
                  {children}
               </LoaderWrapper>
            </ThemeProvider>
         </body>
      </html>
   );
}
